FROM althack/ros2:humble-dev

# Install vrnp mocap from apt
RUN apt update && apt install -y --no-install-recommends \
    gnupg \
    meson \
    curl \
    ninja-build \
    pkg-config \
    libyaml-dev \
    python3-yaml \
    python3-ply \
    python3-jinja2 \
    libevent-dev \
    libdrm-dev \
    libcap-dev \
    python3-pip \
    libeigen3-dev \
    ros-humble-rosbag2-storage-mcap \
    build-essential \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    cmake \
    clang \
    clangd \
    ros-humble-vrpn-mocap* \
    netbase \
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/cache/apt/archives/* \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir \
    numpy \
    scipy

ARG WORKSPACE="/workspaces/ros2_vicon_ws"
RUN echo "if [ -f ${WORKSPACE}/install/setup.bash ]; then source ${WORKSPACE}/install/setup.bash; fi" >> /home/ros/.bashrc
