version: '3.8'

services:
  ros2_vicon_dev_2:
    build:
      context: .
      dockerfile: Dockerfile_humble
      args:
        WORKSPACE: /workspace
    container_name: ros2_vicon_dev_2
    user: ros
    network_mode: host
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ../:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    environment:
      DISPLAY: ${DISPLAY:-:0}
      LIBGL_ALWAYS_SOFTWARE: "1"
    stdin_open: true
    tty: true
    working_dir: /workspace
